# Generated by Django 4.1.3 on 2023-06-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de criacao"),
                ),
                (
                    "modificado",
                    models.DateField(
                        auto_now=True, verbose_name="Data da ultima modificacao"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("assunto", models.CharField(max_length=100, verbose_name="Assunto")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("mensagem", models.TextField(max_length=500, verbose_name="Mensagem")),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
        migrations.CreateModel(
            name="Leads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de criacao"),
                ),
                (
                    "modificado",
                    models.DateField(
                        auto_now=True, verbose_name="Data da ultima modificacao"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("telefone", models.CharField(max_length=100, verbose_name="Telefone")),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
    ]
